[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && remix build"
  publish = "public"

[build.environment]
NPM_FLAGS = "--version" # see https://github.com/netlify/build/issues/1633#issuecomment-907246600

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
