[build]
  publish = "public"
  command = "pnpm run -w build --scope=blog.labeilleviennoise.com --include-filtered-dependencies"

[functions]
  included_files = ["./app/prisma-client/**/*"]

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
