name: Tests
on: push
jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install -g pnpm
    - run: pnpm install --no-frozen-lockfile
    - run: pnpm test

  lint-code:
    needs: install-packages
    runs-on: ubuntu-latest
    steps:
    - run: npm install -g pnpm
    - run: pnpm install --no-frozen-lockfile
    - run: pnpm lint